name: tax_calculator
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0-16.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pinput: ^5.0.2
  fluttertoast: ^9.0.0
  flutter_svg: ^2.0.17
  http: ^1.1.0
  intl: ^0.18.1
  pdf: ^3.10.7
  printing: ^5.11.0
  mono_connect: ^2.1.0
  mono_flutter: ^4.0.4
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.23.5
  fl_chart: ^0.66.2
  firebase_core: ^4.4.0
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
